### ISSUE TITLE
Add followy

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/openAFRICA#12]
Add the followy CKAN extension - https://github.com/CodeForAfricaLabs/ckanext-followy

**Comment by andela-iukwuoma** [comment]
I don't understand what is expected of this Issue. Can you explain @DavidLemayian

**Comment by DavidLemayian** [comment]
@ignatiusukwuoma Simply to add the necessary to `ckan.ini` and `requirements.txt` .

**Comment by DavidLemayian** [comment]
Archiving the followy ckan extension until it is a priority.
