### ISSUE TITLE
Log server errors to Slack

### ISSUE THREAD

**Issue by phillipahereza** [CodeForAfrica/openAFRICA#18]
Whenever the openAFRICA server encounters errors, we should log them on Slack for quick reaction time.

**Comment by DavidLemayian** [comment]
@phillipahereza What's the latest on this?

**Comment by phillipahereza** [comment]
@DavidLemayian I can log events that happen on the dokku container because it has events you can listen to, but I am having a hard logging errors from the app running within the container or finding any documentation on similar work

**Comment by DavidLemayian** [comment]
We're using the dokku-slack plugin instead.
