### ISSUE TITLE
Add Discourse to openAFRICA

### ISSUE THREAD

**Issue by phillipahereza** [CodeForAfrica/openAFRICA#21]
## Description
To improve community engagement, we should deploy discourse for openAFRICA. This forum will then host discussions for HURUmap et al.

## Files
- [Discourse](https://www.discourse.org/)
- [CKAN Discourse Integration](https://github.com/opengov-opendata/ckanext-discourse)

**Comment by DavidLemayian** [comment]
Closing issue to scope out properly with Data Team.
