### ISSUE TITLE
Add ckanext-harvest extension

### ISSUE THREAD

**Issue by tebajanga** [CodeForAfrica/openAFRICA#24]
## Description
Adding ckanext-harvest extension to help the process of fetching / crawling data from different sources.

## Files
https://github.com/CodeForAfricaLabs/ckanext-harvest

## Tasks

 - [ ] Add `ckanext-harvest` as a plugin
 - [ ] Configure at least one source

**Comment by DavidLemayian** [comment]
@tebajanga / @phillipahereza What are the benefits of using this fork?
