### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/openAFRICA#4]
As this is a repo specifically for deployment, we should align our tests in #3 for inclusion in our code integration.

To do this, let's integrate with Travis-CI.

**Comment by dmkitui** [comment]
I undertook to resolve this issue last week. To date, I am still waiting for admin and write access to the repo so I can be able to do the integration.

**Comment by DavidLemayian** [comment]
@dmkitui Emm.. Send a PR. :) Also, Are you able to assign yourself to this issue?

**Comment by dmkitui** [comment]
@DavidLemayian Thank you for the prompt response. Just confirmed we are to work on our forked repo. So will follow-up with our admin for the permissions. Now, just keeping an eye out for any other outstanding issues that need to be sorted. Feel free to alert me. Thank you.
