### ISSUE TITLE
Add feature to allow registration through existing social media and email accounts

### ISSUE THREAD

**Issue by Andretalik** [CodeForAfrica/openAFRICA#5]
Currently in the present project a new user has to manually enter his/her email and set a password.
Adding a socialauth registration and login I believe will add value to the project as it is.

**Comment by DavidLemayian** [comment]
Great idea @Andretalik. Is there an existing extension that does this?

**Comment by Andretalik** [comment]
@DavidLemayian Currently there is none that I could find among the lists of Ckan Extensions.

**Comment by DavidLemayian** [comment]
@Andretalik meaning we'd have to create a new CKAN extension for this. I've created a repo here if you wanna take a stab and creating a list of issues for it - https://github.com/CodeForAfricaLabs/ckanext-socialite

**Comment by Andretalik** [comment]
@DavidLemayian Let me dive right in

**Comment by Andretalik** [comment]
@DavidLemayian Could you add me as a collaborator to the repo?

**Comment by Andretalik** [comment]
@DavidLemayian 
Since this issue will affect the Ckan Project as a whole then I believe raising the some issue in the original C4A Ckan repo will be more effective.

**Comment by DavidLemayian** [comment]
Closing issue to focus on development at https://github.com/CodeForAfricaLabs/ckanext-socialite
